const trechos = [
	'"O frio da montanha corta até a alma, mas o brilho runico que emana do topo do pico não deixa dúvidas: o ritual já começou. Seus companheiros preparam as armas em silêncio. Um trovão ecoa no céu limpo e a pesada porta de carvalho da torre se abre lentamente, convidando vocês para o desconhecido..."',
	'"A névoa na Floresta dos Lamentos é densa demais para enxergar um passo à frente, mas os olhos dourados entre as árvores sabem exatamente onde vocês estão. O ladino sinaliza para parar. Um estalar de galho ecoa no silêncio e o cheiro de ozônio avisa que a magia antiga despertou..."',
	'"O cheiro de hidromel barato e assado preenche o ar abafado da taverna, mas o clima esquenta de verdade quando o estranho encapuzado joga um mapa empoeirado sobre a mesa. Entre manchas de vinho e símbolos esquecidos, uma única rota brilha em vermelho. A aventura finalmente encontrou vocês."',
	'"Chuva ácida reflete as luzes de neon nos paralelepípedos de Neo-Verídia. Seu deck pisca no pulso com um sinal de alerta vermelho: o contrato foi vazado e a corporação já enviou os cães de caça. O barulho de rotores de um drone se aproxima no beco. Hora de plugar e rezar."',
	'"O relógio da catedral marca meia-noite enquanto o aroma de chuva e sangue fresco toma conta do beco escuro. As sombras no final da rua se contorcem e ganham forma. O Príncipe da cidade exigiu uma audiência antes do amanhecer, mas nem todos os Membros da noite jogam pelas regras do Elysium..."',
	'"As velas do santuário tremem sem vento algum, e o cheiro de incenso queimado esconde algo mais amargo por baixo. O oráculo cego ergue a cabeça antes mesmo de vocês entrarem. "Vocês chegaram tarde demais", ela sussurra, "ou cedo demais — ainda não decidi." Os ossos sobre o altar começam a se mover."',
	'"O deserto de vidro racha sob o peso das botas, cada passo ecoando como um sino distante. No horizonte, a caravana em chamas ainda solta fumaça negra contra o céu duplo. Um dos sóis já se põe. Vocês têm até o anoitecer para encontrar os sobreviventes antes que os nômades do vazio cheguem primeiro."',
	'"O elevador industrial range ao descer para os níveis inferiores da colônia, onde a luz artificial já não alcança. O contador Geiger no seu cinto começa a disparar cliques nervosos. Nos monitores quebrados ao longo do corredor, uma mensagem se repete em loop: não desçam mais."',
	'"A biblioteca proibida cheira a papel podre e magia selada, e as correntes na porta principal foram arrombadas por dentro. Pegadas de barro terminam abruptamente no meio do corredor, como se algo tivesse simplesmente deixado de tocar o chão. O bibliotecário-fantasma observa vocês em silêncio, esperando a pergunta certa."',
	'"O trem blindado corta a tundra congelada a toda velocidade, e o rádio só transmite estática há três horas. No vagão de carga, os selos imperiais nas caixas foram violados — não por fora, mas por dentro. Alguém, ou algo, quer muito que essa carga nunca chegue ao seu destino."',
	'"A maré vazou de repente, deixando o casco do navio afundado exposto pela primeira vez em séculos. Cracas e limo cobrem símbolos que ninguém deveria ler em voz alta. O capitão do porto se recusa a se aproximar. Sobra para vocês descobrir o que dormiu ali tanto tempo, e por que acordou agora."',
	'"O sino da vila toca fora de hora, um alarme que ninguém ouvia há gerações. Portas se fecham, cortinas se cerram, e um silêncio pesado desce sobre a praça vazia. Do topo da colina, uma procissão de tochas desce lentamente em sua direção. Ninguém quer contar a vocês o que ela significa."',
	'"A estação espacial abandonada gira em silêncio absoluto, seus corredores iluminados apenas por luzes de emergência piscando em vermelho. O log de bordo termina no meio de uma frase. Nos monitores da ponte, um contador regressivo continua correndo — e ninguém sabe o que acontece quando chegar a zero."',
	'"O portal de pedra pulsa com uma luz azulada que não existe em nenhum livro de magia conhecido. Os símbolos ao redor da moldura mudam de posição quando ninguém olha diretamente para eles. O guardião caído ao lado ainda segura a espada erguida, como se tivesse sido petrificado no meio de um golpe."',
	'"O leilão clandestino acontece três andares abaixo da rua, num salão forrado de veludo e segredos. O item da noite chega coberto por um pano negro, escoltado por guardas que não piscam. Quando o pano cai, um silêncio gelado toma conta da sala — e os lances começam antes mesmo do martelo bater."',
	'"A aurora sobre a Cidadela Flutuante tinge as torres de um dourado quase sagrado, mas o sino de emergência já soa há minutos. Correntes de ferro se partem no cais aéreo e uma das ilhas menores começa lentamente a despencar. Alguém sabotou os cristais de sustentação, e o tempo está se esgotando."',
	'"O laboratório subterrâneo ainda cheira a formol e ozônio, mesmo décadas depois do incidente. Os tanques de contenção estão vazios, os vidros estilhaçados para fora, não para dentro. No quadro branco manchado de ferrugem, uma única frase sobrevive: eles não sabiam que era recíproco."',
	'"O carnaval de máscaras encobre rostos e intenções em partes iguais, enquanto a orquestra toca uma valsa estranhamente lenta para a ocasião. No meio da pista, uma figura de máscara branca lisa observa vocês sem se mover. Quando a música para, ela será a única a continuar dançando."',
	'"O farol pisca em um padrão que nenhum manual de navegação reconhece, guiando os navios não para o porto, mas para os recifes. O faroleiro não responde ao rádio há semanas. Na trilha até a torre, pegadas descalças vão na direção certa, mas nenhuma delas volta."'
]

export { trechos }